services:
    portainer-ce:
        ports:
            - 9000:9000
            - 9443:9443
        container_name: portainer-srv
        restart: always
        volumes:
            - /home/xero/.config/appdata/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        image: portainer/portainer-ce:latest
volumes:
    data:
